use mellowmesh_client::MellowMeshClient;
use mellowmesh_core::agent::AgentRegistration;
use mellowmesh_core::message::Message;
use futures_util::StreamExt;
use std::time::Duration;

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    println!("Connecting to MellowMesh daemon...");
    let client = MellowMeshClient::connect().await?;
    println!("Connected successfully!");

    // 1. Register the agent
    let agent_id = "agent://yannick/Hermes".to_string();
    let agent_name = "Hermes".to_string();
    let owner_id = "human://yannick".to_string();
    println!("Registering agent: {} (Name: '{}')", agent_id, agent_name);

    let reg = AgentRegistration {
        id: agent_id.clone(),
        name: agent_name.clone(),
        owner: owner_id.clone(),
        mode: "autonomous".to_string(),
        capabilities: vec!["analysis".to_string()],
    };
    client.register_agent(&reg).await?;

    // 2. Subscribe to the agent's inbox topic
    // Topic: _agent.<owner>.<name>.inbox -> _agent.yannick.Hermes.inbox
    let inbox_topic = "_agent.yannick.Hermes.inbox";
    println!("Subscribing to inbox topic: '{}'...", inbox_topic);
    let mut inbox_stream = client.subscribe(inbox_topic).await?;

    // 3. Publish a message to a forum channel containing the @mention
    let forum_topic = "_forum.general";
    let message_body = "Hello @Hermes, can you analyze the latest system logs?";
    println!(
        "\n[Publisher] Publishing message to '{}':\n  \"{}\"",
        forum_topic, message_body
    );

    let msg = Message {
        id: String::new(), // Auto-generated by daemon
        topic: forum_topic.to_string(),
        from: "human://yannick".to_string(),
        owner: Some("human://yannick".to_string()),
        timestamp: chrono::Utc::now(),
        content_type: "text/plain".to_string(),
        body: message_body.to_string(),
        headers: None,
        payload: None,
        parent_id: None,
    };
    client.publish(&msg).await?;

    // 4. Wait for the routed copy in the agent's inbox
    println!("\n[Agent] Listening for messages in the inbox (waiting up to 5 seconds)...");
    if let Some(msg_result) = tokio::time::timeout(Duration::from_secs(5), inbox_stream.next()).await.ok() {
        if let Some(Ok(received_msg)) = msg_result {
            println!("\n[Agent] SUCCESS! Received routed message in inbox!");
            println!("  From Topic:     {}", received_msg.topic);
            println!("  From Sender:    {}", received_msg.from);
            println!("  Rewritten Body: {}", received_msg.body);
            if let Some(ref headers) = received_msg.headers {
                if let Some(mentions) = headers.get("x-mentions") {
                    println!("  Mentions Header: {}", mentions);
                }
            }
            
            // Basic assertions
            assert!(received_msg.body.contains("[@Hermes](agent://yannick/Hermes)"));
            assert_eq!(received_msg.topic, inbox_topic);
            println!("\nMention routing verification passed!");
        } else {
            eprintln!("Error receiving message from stream.");
        }
    } else {
        eprintln!("Timeout waiting for routed message in agent's inbox.");
        eprintln!("Ensure the mellowmesh daemon is running locally on port 40000.");
    }

    Ok(())
}
